export type TradeRecord = {
  id: string;
  tradeDate: string; // yyyy-MM-dd
  entryTime: string; // ISO
  exitTime: string | null;
  symbol: string;
  market: string;
  direction: "LONG" | "SHORT" | string;
  positionSize: number;
  entryPrice: number;
  exitPrice: number | null;
  stopLoss: number | null;
  takeProfit: number | null;
  grossPnl: number;
  fees: number;
  netPnl: number;
  riskAmount: number | null;
  rewardAmount: number | null;
  plannedRr: number | null;
  rMultiple: number | null;
  pnlPercent: number | null;
  result: "WIN" | "LOSS" | "BREAKEVEN" | string;
  strategyId: string | null;
  strategyName: string | null;
  setupId: string | null;
  setupName: string | null;
  sessionId: string | null;
  sessionName: string | null;
  marketCondition: string | null;
  confidenceBefore: number | null;
  emotionBefore: string | null;
  emotionAfter: string | null;
  followedPlan: boolean | null;
  setupQuality: number | null;
  executionQuality: number | null;
  disciplineScore: number | null;
  thesis: string | null;
  reasonEntry: string | null;
  reasonExit: string | null;
  whatWentWell: string | null;
  whatWentWrong: string | null;
  lesson: string | null;
  notes: string | null;
  isDemo: boolean;
  tags: { id: string; name: string; color: string }[];
  mistakes: { id: string; name: string }[];
  confluences: { id: string; name: string }[];
  imageCount: number;
};

export type TradeFilters = {
  from?: string;
  to?: string;
  range?: string;
  symbols?: string[];
  markets?: string[];
  directions?: string[];
  results?: string[];
  setupIds?: string[];
  strategyIds?: string[];
  sessionIds?: string[];
  tagIds?: string[];
  mistakeIds?: string[];
  confluenceIds?: string[];
  followedPlan?: "yes" | "no";
  rMin?: number;
  rMax?: number;
  pnlMin?: number;
  pnlMax?: number;
  search?: string;
  includeDemo?: boolean;
};
